title: Nashville Music Hackthon
description: > # this means to ignore newlines until "baseurl:"
  Inspired by the NY Monthly Music Hackathon, the Nashville Music 
                                    Hackathon brings together local musicians, programmers, designers, composers, 
                                    hardware tinkerers and fans for a day of learning and creating at the intersection of music and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "dev.nashvillemusichackathon.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/static/img/icon-large.png"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_past_event_pages', '_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/nashvillemusictech/
  - title: twitter
    url: https://twitter.com/nash_musictech

permalink: pretty

sass:
  sass_dir: _sass
  style: compressed
