title: Nashville Music Hackthon
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/nashville-music-hackathon" # the subpath of your site, e.g. /blog
url: "coreyar.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/static/img/icon-large.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/groups/nashvillemusictech/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_past_event_pages', '_2018_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/nashvillemusictech/
  - title: twitter
    url: https://twitter.com/nash_musictech

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed